### PR TITLE
The plugin should log the locations where the reports are looked for

### LINKED ISSUE #256: The plugin should log the locations where the reports are looked for
This is a usability improvement and should make the live of Sonar admins a little easier: the plugin should point (in the logs) to the exact directories where the reports are expected (according to the current configuration). Currently, we log only the pattern used for the search, which is less clear.

Has also the potential to save us quite a few support cases.

### PR DESCRIPTION
**Pull request by guwirth**
- add unique 'parsing report' information to all sensors
- log canonical path
- close #256

### CODE REVIEW

**Comment by Bertk** [comment]
This looks somehow redundant to me - we have a logging in CxxReportSensor.analyse()
```
        CxxUtils.LOG.info("Processing report '{}'", report);
```
adding this PR the log file contains:
```
08:31:45.496 INFO  - Parsing the XML report rats-report.xml
08:31:45.498 INFO  - Processing report 'C:\Server\module\Source\component\rats-report.xml'
08:31:45.499 INFO  - Parsing report (RATS) 'C:\Server\module\rats-report.xml'
08:31:45.516 INFO  - RATS issues processed = 6
08:31:45.516 INFO  - Sensor CxxRatsSensor done: 23 ms
```
I use a multi-module configuration (Analysis Bootstrapper for Visual Studio Projects Plugin) and the reported filename is not correct (does not exist).
I removed CxxUtils.fileToCanonicalPath() and used only the 'File report' parameter which shows the correct file name. I feel the path resolution should be handled in only in CxxReportSensor and not within the tool sensor.

**Comment by guwirth** [comment]
Understanding the original request from @wenns right?
- He like to have unique messages in all sensors. Was not the case, each sensor was writing something different or nothing. So I added this unique message to all parse... methods. But maybe inside parse... the message should be only 'parsing 'xxx' format' without the path?
- second requirement was to see always the absolute path
But thanks for the feedback will check this again.

**Comment by Bertk** [comment]
Shouldn't individual settings for the coverage parsers be used instead of the processing chain?
```
08:34:03.627 INFO  - Parsing the XML report *.coveragexml
08:34:03.644 INFO  - Parsing report (Cobertura) ''C:\Server\module\xml.coveragexml'
08:34:03.653 INFO  - Parsing report (Bullseye) 'C:\Server\module\xml.coveragexml'
08:34:03.660 INFO  - Parsing report (Visual Studio) 'C:\Server\module\xml.coveragexml'
08:34:03.678 INFO  - Added report 'C:\Server\module\Source\component\xml.coveragexml' (parsed by: VisualStudioParser) to the coverage data
```
This is done this way in the .net test library (see https://github.com/SonarCommunity/sonar-dotnet-tests-library/blob/master/src/main/java/org/sonar/plugins/dotnet/tests/CoverageConfiguration.java)

**Comment by guwirth** [comment]
@Bertk could you try again please.

- unify method name: processReport
- unify processReport parameters: final Project project, final SensorContext context, File report
- add format info to all parser: CxxUtils.LOG.info("Parsing 'XXX' format");
- all sensors are derived from 'CxxReportSensor' but some has own 'analyse' methods and do not output 'CxxUtils.LOG.info("Processing report '{}'", report);' message. Add this message to sensors with own analyze methods.
- change 'getReports': create canonical paths

**Comment by Bertk** [comment]
Sure, but I am traveling right now and will check it when I am back.

**Comment by Bertk** [comment]
Looks OK :+1:
```
 14:59:58.462 INFO  - Processing report 'c:\xxx\cppcheck-report.xml'
 14:59:58.462 INFO  - Parsing 'Cppcheck V2' format
 14:59:58.946 INFO  - Processing report 'c:\xxx\pclint-report.xml'
 14:59:58.946 INFO  - Parsing 'PC-Lint' format
 15:00:58.196 INFO  - Processing report 'c:\xxx\compiler-report.log'
 15:00:58.196 INFO  - Parsing 'Visual C++' format
 15:06:50.808 INFO  - Processing report 'c:\xxx\vera-report.xml'
 15:06:50.808 INFO  - Parsing 'Vera++' format
```

**Pull request merged**
