### PR TITLE
add build for windows

### PR DESCRIPTION
**Pull request by jmecosta**
this add build for windows...  current sources are not building on windows... 

we need to setup a build in appveyour:

@guwirth can you check if after you create a account in appveyour are you able to setup builds for wenns/cxxplugin?

no additicional configuration is needed after this yml is created. see my account: https://ci.appveyor.com/project/jorgecosta/sonar-cxx

### CODE REVIEW

**Comment by guwirth** [comment]
> .... are you able to setup builds for wenns?

No I'm sorry.

**Comment by jmecosta** [comment]
@wenns can you do it?

**Comment by jmecosta** [comment]
@guwirth rebase and tests are now passing on windows:
https://ci.appveyor.com/project/jorgecosta/sonar-cxx

artifacts created: https://ci.appveyor.com/project/jorgecosta/sonar-cxx/build/artifacts 

we should also use badges in the readme to show the build is green:
https://ci.appveyor.com/api/projects/status/mi5ft6fo1qx3q8o7?svg=true

**Comment by guwirth** [comment]
Hi @jmecosta really cool. We should link the final artifacts somehow. As far as I understand the plugin binary is created with every merge => #293 ?

**Comment by jmecosta** [comment]
Appveyour supports deployment of artifact to github, it can even do release for you if you want base on tag.

Question here is how to enable the build if you can't access weens repository

**Comment by jmecosta** [comment]
@guwirth, @wenns what about if moving the repository inot one organization, permissions are better handle like that and its possible to any user to configure builds for a certain repository

**Comment by guwirth** [comment]
> inot one organization

 What do you mean with this?

Heard also nothing from @wenns for a longer time. So I'm also interested in his opinion how to continue...

**Comment by jmecosta** [comment]
@guwirth https://github.com/SonarCommunity is a organization. i am for example in these
image

and i can setup builds for any of the projects in those organizations. we could call it SonarOpenCommunity

**Comment by wenns** [comment]
Hi @guwirth, @jmecosta, 

Im not opposed to moving the repository into such an organisation. My situation is changed and I cannot participate in further development much, anyway. And I'm grateful to you guys for maintaining this code base.

As for the actual transfer: just say what I should do and I will transfer the repo.

**Comment by jmecosta** [comment]
good to hear from you @wenns . @guwirth if you are ok with it, i can create the organization and give admin permissions to you and wenns?

any suggestiongs for the name? i gave SonarOpenCommunity

**Comment by guwirth** [comment]
@jmecosta it is ok for me to move it to an organization. With the name I'm not sure because Sonar, SonarQube and SonarSource are protected trademarks. Also it depends a little bit if only cox plugin should be in the organization or more?

**Comment by jmecosta** [comment]
using sonar as part of a bigger word its perfectly ok, sonar is not trademark of sonarsource, thats the reason they add to change it to SonarQube, however Sonar is still used in SonarQube and there is no problems with it....

SonarOpenCommunity, or SonarCxxCommunity are perfectly fine. Both, i think they can have more than just the cxx plugin for sure, if choosing the first we are stating that anything not related with cxx plugin can be made available if choosing the later we are stating only cxx ecosystem tools will be available.

Really depends were we want to go with this, i for first have a couple of plugins that i would not mind having them there. like sonar.msbuild.plugin, sonar.fsharp.pluig, sonar.xaml.plugin. also nuget tasks to support cxx plugin etc.

this all organization business is very flexible, you can move those repos when you want and to where you want

**Comment by guwirth** [comment]
I tend to SonarOpenCommunity.

**Comment by jmecosta** [comment]
Lets try it then

**Comment by jmecosta** [comment]
@guwirth done, can you transfer the repo. If not @wenns can you do it. (afte that you can clone so that the repository still exist at your side)

**Comment by guwirth** [comment]
@jmecosta don't have access. @wenns has  to do it.

**Comment by wenns** [comment]
Its done

**Comment by jmecosta** [comment]
Thanks @wenns

**Comment by guwirth** [comment]
@wenns thanks a lot for your cpntribution the last years. It's really a pity that you have no more time for doing this...

**Comment by Bertk** [comment]
@wenns thanks a lot for you advices and for your work on SonarQube C++ community plug-in.

**Comment by jmecosta** [comment]
@wenns thank you a lot also for starting this project, and hopefully you can still contribute some time in future. we try to maintain it as possible

**Comment by wenns** [comment]
Thanks for taking over. It would be a real pity to see this code decay. Keep up good work, guys!

**Pull request merged**
