### PR TITLE
Update VC++ compiler rules

### PR DESCRIPTION
**Pull request by Bertk**
- add MSDN references
- 12 additional rules

### CODE REVIEW

**Comment by guwirth** [comment]
Thx.  Could you rebase it please.

**Comment by Bertk** [comment]
@guwirth Rebasing is not necessary. Please give me a hint why you think I should do it.

**Comment by guwirth** [comment]
To avoid side effects I like to merge features only after rebase and squash. Makes it much easier… at least for me.

**Comment by Bertk** [comment]
@guwirth I understand your request. Nevertheless rebasing is not necessary because I created this branch this weekend based on a synched master and the affected 2 files were not motified the last 2 months.

**Pull request merged**
