### PR TITLE
Bugfix/mm bertk

### PR DESCRIPTION
**Pull request by jmecosta**

### CODE REVIEW

**Comment by jmecosta** [comment]
for the sake of review, ive reverted the line endings. they can be normalized after the review. 

@Bertk please confirm this is the required functionality as i cannot test this

**Comment by Bertk** [comment]
Yes, this solves the multi model issues for the relative include paths :satisfied:

**Comment by guwirth** [comment]
@jmecosta Is this ready to merge?

**Comment by jmecosta** [comment]
Yes

**Pull request merged**
