### PR TITLE
add sonarqube-5.2-RC2 to Travis

### PR DESCRIPTION
**Pull request by guwirth**

### CODE REVIEW

**Comment by guwirth** [comment]
Getting this new warning with SQ 5.2. Don't know why?
```
 Assertion Failed: Found following errors and/or warnings lines in the logfile:
      10:44:00.604 WARN  - Unable to get a valid mac address, will use a dummy address
      For details see _coverage_project_.log
```

**Comment by guwirth** [comment]
Seems there is a problem  to access the analysis log. This is different with SQ 5.2? Think SQ will create it on server side and provide it delayed?

**Comment by jmecosta** [comment]
Yep but you need to access the ui, I think there is also some rest api for
this. At least I've seen something I'm the api. I've raise a question about
this in the forum that we now don't know if analysis is OK or not even if
its ok locally

**Comment by guwirth** [comment]
Natural solution would be to have an option in sonar runner to wait for the result and provide it on client side.

**Comment by jmecosta** [comment]
Right, but I guess the only possible workaround is to poll the server after
each test

**Comment by guwirth** [comment]
* update links to https://sonarsource.bintray.com/Distribution/sonarqube
* add '.*WARN.*Unable to get a valid mac address, will use a dummy address' to integration tests
* mark SQ 5.2 as allowed to fail
* build will fail as soon as a job has failed, or when the only jobs left allows failures
* close #648

**Pull request merged**
