### PR TITLE
Allow absolute report path to fix issue #278, which can help for issue #252

### PR DESCRIPTION
**Pull request by jfallot**

### CODE REVIEW

**Comment by wenns** [comment]
Thanks for the PR. I do not, however, think that this is the right solution for issues with multi-module setups. I'll return to this after the release.

**Comment by jfallot** [comment]
@wenns: A better solution to help in case of multi-module setups is welcome. This PR is however focused on allowing absolute report paths, which can be useful in multiple cases (although not all as @jmecosta mentionned). For the time being, I continue using my own fork.

**Comment by jmecosta** [comment]
@JF https://github.com/wenns/sonar-cxx/pull/358 should handle your use
case... or if not can you produce a example project where you are unable to
import reports using the current relative paths (once #358 is merged)

**Comment by jfallot** [comment]
@jmecosta, it looks like https://github.com/wenns/sonar-cxx/pull/358 is still "Work in progress" and it looks too early for me to make a try with it.
I will try to build a sample project showing that absolute report path is needed.

**Comment by jmecosta** [comment]
it should be green now, but its not :) for some reason. they are passing in my environment. i need to check in unix

**Comment by jmecosta** [comment]
seems http://sonarqube.15.x6.nabble.com/Trying-to-get-gcov-reports-working-td5031007.html the c++ sonar source allows absolute paths... probably you should do the same...

**Comment by guwirth** [comment]
Seems to be outdated.
Update PR if still needed.

**Pull request closed without merging**
