### PR TITLE
fix sqale definitions

### PR DESCRIPTION
**Pull request by jmecosta**
jump version to 0.9.4 snashot improve some sqale difintions that cause some local analysis failure

### CODE REVIEW

**Comment by guwirth** [comment]
To merge it pom files (version 0.9.4) should be removed.

**Comment by jmecosta** [comment]
Dont we increment the versions straight after a release?

**Comment by guwirth** [comment]
No, see https://github.com/wenns/sonar-cxx/wiki/Release-Procedure, that is the last step.

**Comment by jmecosta** [comment]
We need to adjust this, usually we need to provide snapshot versions for
users to use to verify defects. We should not provide the same 0.9.3
because it has been released.

IMO the 0.9.4-snapashot should be the first commit after a release. The
same happens with all plugins in sonar community

**Comment by guwirth** [comment]
Hi Jorge. Your are right I'm wrong. Didn't see the SNAPSHOT after the version number, sorry.

**Comment by jmecosta** [comment]
But no need to merge already, let's see if someone can test this

**Pull request merged**
