### PR TITLE
Generate public API documentation violation for alias declaration

### LINKED ISSUE #577: Type alias (using =) does not generate public API documentation violation
Hi,

I have a class with a type alias
```
class A
{
public:
   using X = int;
   typedef int Y;
};
```
This does not generate a public API documentation violation, although the typedef does.

### PR DESCRIPTION
**Pull request by lcintrat**
Fix #577

### CODE REVIEW

**Comment by guwirth** [comment]
@lcintrat Looks good. Only hint: you check not all getNext..., getFirst... for null. But don't know if this is always needed?

**Comment by lcintrat** [comment]
@guwirth You are right, I rely on the parser. I assume that if the parsing passed, then the searched node is present (according to the grammar).
I can add checks for null, but what is the rule on error? Error message or is there a mean to create a SQ issue for that?

**Comment by guwirth** [comment]
@lcintrat it should at least not crash.
Some grammar parts are optional, error recovery could be enabled, ...
Can speak only how I do it. If return value could be null I always check it.

**Comment by lcintrat** [comment]
:+1:

**Comment by guwirth** [comment]
@lcintrat if finished please rebase & squash. I will merge it then.

**Comment by lcintrat** [comment]
Done

**Pull request merged**
