### PR TITLE
remove deprecated fromIOFile

### LINKED ISSUE #600: PC-lint report may create SonarException in decorator
A rare scenario will create a java.lang.ArrayIndexOutOfBoundsException in decorator.
This will happen whenever a issue is detected after the complete file was processed e.g.
```number = "766" desc = "Header file 'some-header.h' not used in module 'src\mysource.cpp'"``` and there is no empty line at the end of the file. The line number for the issue in the PC-lint report file is incremented by 1 compared to the number of lines in the source file.

This was observed with SQ 5.1.1 and the C++ community plug-in.

Possible Solutions:
a) Add an empty line at the end of the source files
b) Correct the line number of the issue from the Report and set it to line=0 or the value for the last line.

### LINKED ISSUE #625: Execute decorators failing
Have some projects which are failing after **Execute decorators** (SQ 5.1.1 & CXX 0.9.4). I don't know why? Someone an idea?

```
13:02:36.129 INFO  - Execute decorators...
13:02:36.129 DEBUG - Decorators: ManualMeasureDecorator -> QProfileEventsDecorator -> org.sonar.batch.design.ProjectDsmDecorator@7dc56c0a -> org.sonar.batch.design.SubProjectDsmDecorator@6c4de249 -> org.sonar.batch.design.DirectoryDsmDecorator@3c73a08e -> FileTangleIndexDecorator -> SumDuplicationsDecorator -> UnitTestDecorator -> org.sonar.plugins.core.security.ApplyProjectRolesDecorator@4f8365b2 -> org.sonar.plugins.core.sensors.DirectoriesDecorator@73990c4d -> org.sonar.plugins.core.sensors.FilesDecorator@5a2adcd -> org.sonar.plugins.core.timemachine.TimeMachineConfigurationPersister@27e05d64 -> org.sonar.plugins.core.timemachine.NewCoverageAggregator@6e3a9891 -> f(lines) -> f(generated_lines) -> f(ncloc) -> f(generated_ncloc) -> f(classes) -> f(packages) -> f(functions) -> f(accessors) -> f(statements) -> f(public_api) -> f(comment_lines) -> f(public_undocumented_api) -> f(commented_out_code_lines) -> f(complexity) -> f(complexity_in_classes) -> f(complexity_in_functions) -> f(class_complexity_distribution) -> f(function_complexity_distribution) -> f(file_complexity_distribution) -> f(lines_to_cover) -> f(uncovered_lines) -> f(conditions_to_cover) -> f(uncovered_conditions) -> f(it_lines_to_cover) -> f(it_uncovered_lines) -> f(it_conditions_to_cover) -> f(it_uncovered_conditions) -> f(overall_lines_to_cover) -> f(overall_uncovered_lines) -> f(overall_conditions_to_cover) -> f(overall_uncovered_conditions) -> f(rfc) -> f(rfc_distribution) -> f(lcom4_distribution) -> f(package_cycles) -> f(package_tangles) -> f(package_feedback_edges) -> f(package_edges_weight) -> f(new_lines_to_cover) -> f(new_uncovered_lines) -> f(new_conditions_to_cover) -> f(new_uncovered_conditions) -> f(new_it_lines_to_cover) -> f(new_it_uncovered_lines) -> f(new_it_conditions_to_cover) -> f(new_it_uncovered_conditions) -> f(new_overall_lines_to_cover) -> f(new_overall_uncovered_lines) -> f(new_overall_conditions_to_cover) -> f(new_overall_uncovered_conditions) -> org.sonar.batch.language.LanguageDistributionDecorator@1b19e5bf -> DirectoryTangleIndexDecorator -> org.sonar.batch.cpd.decorators.DuplicationDensityDecorator@6f7cc804 -> CommentDensityDecorator -> f(file_complexity) -> f(class_complexity) -> f(function_complexity) -> org.sonar.plugins.core.sensors.LineCoverageDecorator@fdc872e -> org.sonar.plugins.core.sensors.CoverageDecorator@b484c37 -> org.sonar.plugins.core.sensors.BranchCoverageDecorator@71f1ea35 -> org.sonar.plugins.core.sensors.ItLineCoverageDecorator@3d4cae3f -> org.sonar.plugins.core.sensors.ItCoverageDecorator@5642ab4f -> org.sonar.plugins.core.sensors.ItBranchCoverageDecorator@1f227c44 -> org.sonar.plugins.core.sensors.OverallLineCoverageDecorator@617c9dd7 -> org.sonar.plugins.core.sensors.OverallCoverageDecorator@3999ea91 -> org.sonar.plugins.core.sensors.OverallBranchCoverageDecorator@7ac2263e -> Common Rules for c++ -> org.sonar.batch.issue.tracking.IssueTrackingDecorator@7aa5596f -> org.sonar.batch.debt.DebtDecorator@4778db1f -> org.sonar.batch.debt.NewDebtDecorator@3d356e85 -> CountUnresolvedIssuesDecorator -> CountFalsePositivesDecorator -> org.sonar.batch.debt.SqaleRatingDecorator@3e159f12 -> com.gistlabs.sonar.plugins.dplplugin.DPLDecorator@6d9c656d -> org.sonar.plugins.core.timemachine.TendencyDecorator@6d093764 -> VariationDecorator
13:02:36.178 DEBUG - Release semaphore on project : org.sonar.api.resources.Project@357a3cb9[id=1533,key=XXX,qualifier=TRK], with key batch-XXX
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
Total time: 12.230s
Final Memory: 23M/823M
INFO: ------------------------------------------------------------------------
```
Normally it should continue like this:
```
13:02:46.422 DEBUG - Decorator time:
	ManualMeasureDecorator: 188ms
	QProfileEventsDecorator: 10ms
	org.sonar.batch.design.ProjectDsmDecorator@664a3770: 0ms
	org.sonar.batch.design.SubProjectDsmDecorator@63a7a23a: 1ms
	org.sonar.batch.design.DirectoryDsmDecorator@785e236f: 2ms
	FileTangleIndexDecorator: 0ms
	SumDuplicationsDecorator: 2ms
	UnitTestDecorator: 0ms
	org.sonar.plugins.core.security.ApplyProjectRolesDecorator@48afc94c: 3ms
	org.sonar.plugins.core.sensors.DirectoriesDecorator@51dc7140: 0ms
	org.sonar.plugins.core.sensors.FilesDecorator@d9347e: 1ms
	org.sonar.plugins.core.timemachine.TimeMachineConfigurationPersister@1a0108a5: 4ms
	org.sonar.plugins.core.timemachine.NewCoverageAggregator@7e88ba07: 1ms
	f(lines): 0ms
	f(generated_lines): 0ms
	f(ncloc): 0ms
	f(generated_ncloc): 0ms
	f(classes): 0ms
	f(packages): 0ms
	f(functions): 1ms
	f(accessors): 0ms
	f(statements): 0ms
	f(public_api): 0ms
	f(comment_lines): 0ms
	f(public_undocumented_api): 0ms
	f(commented_out_code_lines): 0ms
	f(complexity): 0ms
	f(complexity_in_classes): 0ms
	f(complexity_in_functions): 0ms
	f(class_complexity_distribution): 0ms
	f(function_complexity_distribution): 6ms
	f(file_complexity_distribution): 1ms
	f(lines_to_cover): 0ms
	f(uncovered_lines): 0ms
	f(conditions_to_cover): 0ms
	f(uncovered_conditions): 0ms
	f(it_lines_to_cover): 0ms
	f(it_uncovered_lines): 0ms
	f(it_conditions_to_cover): 0ms
	f(it_uncovered_conditions): 0ms
	f(overall_lines_to_cover): 0ms
	f(overall_uncovered_lines): 0ms
	f(overall_conditions_to_cover): 0ms
	f(overall_uncovered_conditions): 0ms
	f(rfc): 0ms
	f(rfc_distribution): 0ms
	f(lcom4_distribution): 0ms
	f(package_cycles): 0ms
	f(package_tangles): 0ms
	f(package_feedback_edges): 0ms
	f(package_edges_weight): 0ms
	f(new_lines_to_cover): 0ms
	f(new_uncovered_lines): 0ms
	f(new_conditions_to_cover): 1ms
	f(new_uncovered_conditions): 0ms
	f(new_it_lines_to_cover): 1ms
	f(new_it_uncovered_lines): 0ms
	f(new_it_conditions_to_cover): 0ms
	f(new_it_uncovered_conditions): 0ms
	f(new_overall_lines_to_cover): 0ms
	f(new_overall_uncovered_lines): 0ms
	f(new_overall_conditions_to_cover): 0ms
	f(new_overall_uncovered_conditions): 0ms
	org.sonar.batch.language.LanguageDistributionDecorator@4e023095: 6ms
	DirectoryTangleIndexDecorator: 0ms
	org.sonar.batch.cpd.decorators.DuplicationDensityDecorator@6afe49f5: 0ms
	CommentDensityDecorator: 1ms
	f(file_complexity): 1ms
	f(class_complexity): 0ms
	f(function_complexity): 0ms
	org.sonar.plugins.core.sensors.LineCoverageDecorator@1ff84804: 1ms
	org.sonar.plugins.core.sensors.CoverageDecorator@1fba5aad: 1ms
	org.sonar.plugins.core.sensors.BranchCoverageDecorator@4837635d: 1ms
	org.sonar.plugins.core.sensors.ItLineCoverageDecorator@472ea479: 0ms
	org.sonar.plugins.core.sensors.ItCoverageDecorator@1acb7cf0: 1ms
	org.sonar.plugins.core.sensors.ItBranchCoverageDecorator@57e92236: 1ms
	org.sonar.plugins.core.sensors.OverallLineCoverageDecorator@24378e1d: 1ms
	org.sonar.plugins.core.sensors.OverallCoverageDecorator@1608fb8e: 0ms
	org.sonar.plugins.core.sensors.OverallBranchCoverageDecorator@57653943: 0ms
	Common Rules for c++: 8ms
	org.sonar.batch.issue.tracking.IssueTrackingDecorator@7f9c9fce: 50ms
	org.sonar.batch.debt.DebtDecorator@5fc4773e: 378ms
	org.sonar.batch.debt.NewDebtDecorator@5a14cfa4: 3ms
	CountUnresolvedIssuesDecorator: 15ms
	CountFalsePositivesDecorator: 9ms
	org.sonar.batch.debt.SqaleRatingDecorator@1f76b33a: 4ms
	com.gistlabs.sonar.plugins.dplplugin.DPLDecorator@2d907fcc: 1ms
	org.sonar.plugins.core.timemachine.TendencyDecorator@1f0b18ed: 51ms
	VariationDecorator: 0ms

13:02:46.422 INFO  - Store results in database
13:02:46.422 DEBUG - Execute org.sonar.batch.phases.GraphPersister
13:02:46.430 DEBUG - Execute org.sonar.batch.index.SourcePersister
13:02:46.820 DEBUG - Execute org.sonar.batch.index.ResourcePersister
13:02:46.820 DEBUG - Execute org.sonar.batch.index.MeasurePersister
13:02:50.897 DEBUG - Updating semaphore batch-XXX
13:02:50.951 DEBUG - Execute org.sonar.batch.index.DuplicationPersister
13:02:51.043 INFO  - Analysis reports generated in 80ms, dir size=77 KB
13:02:51.105 INFO  - Analysis reports compressed in 62ms, zip size=48 KB
13:02:51.105 DEBUG - Publish results
13:02:51.712 INFO  - Analysis reports sent to server in 607ms
13:02:51.713 INFO  - ANALYSIS SUCCESSFUL, you can browse http://xxx.com:9000/dashboard/index/XXX
13:02:51.713 INFO  - Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report.
13:02:51.713 DEBUG - Release semaphore on project : org.sonar.api.resources.Project@44e49229[id=7320,key=XXX,qualifier=TRK], with key batch-XXX
...
```

### LINKED ISSUE #629: Remove deprecated fromIOFile
**fromIOFile** is deprecated, see http://javadocs.sonarsource.org/4.5.2/apidocs/deprecated-list.html.

Looking how others did it:
* sonar-python: https://github.com/SonarCommunity/sonar-python/commit/d98787e7416ac93215bb3111b7ffbf38a50e49d9
* sonar-javascript: https://github.com/SonarCommunity/sonar-javascript/commit/992d3a563a55db13040d8dbffd147dfb2ce0f4e9

### PR DESCRIPTION
**Pull request by guwirth**
- close #629
- replace File.fromIOFile with FileSystem.inputFile
- replace org.sonar.api.resources.File with org.sonar.api.batch.fs.InputFile
- use org.sonar.api.batch.fs.internal.DefaultFileSystem in unit tests
- add addInputFile to TestUtils: all files listed in report files must be added to DefaultFileSystem
   - for reports with absolute paths there are two versions needed: one for Window and one for Linux
- close #611, close #600, close #625: add fix for https://jira.sonarsource.com/browse/SONAR-6792

### CODE REVIEW

**Comment by guwirth** [comment]
@jmecosta & @Bertk: PR is ready to review and test. Are there any changes in performance on your environment?

**Comment by jmecosta** [comment]
I will try during this week and report back

**Comment by guwirth** [comment]
Did a comparison between SQ 3.7.4 / CXX plugin 0.9.1 and SQ 5.1.1 / CXX plugin 0.9.4 & this PR:
SQ 5.1.1 & this PR is between 30% and 200% faster.

**Comment by jmecosta** [comment]
got 1 failed tests in the bullseye coverage test in windows, will comment and proceed with test in server

  //@Test
  public void shoulParseTopLevelFiles() {

**Comment by guwirth** [comment]
@jmecosta Strange. Developing and testing only on Windows and it is working fine on my system?

**Comment by jmecosta** [comment]
java 8?

**Comment by jmecosta** [comment]
ok, so its because of this:

22:15:11.133 [main] INFO  CxxPlugin - Added report 'D:\Development\SonarQube\cxx\sonar-cxx\sonar-cxx-plugin\target\test-classes\org\sonar\plugins\cxx\reports-project\coverage-reports\bullseye\bullseye-coverage-drive-letter-without-slash-win.xml' (parsed by: BullseyeParser) to the coverage data
22:15:13.879 [main] DEBUG CxxPlugin - Saving coverage measures for file 'E:\anotherincludeattop.h'
22:15:13.892 [main] DEBUG CxxPlugin - Saving coverage measures for file 'E:\test2\test2.c'
22:15:13.893 [main] DEBUG CxxPlugin - Saving coverage measures for file 'E:\main.c'
22:15:13.895 [main] WARN  CxxPlugin - Cannot find the file 'E:\Test\test.c', ignoring coverage measures

Test is capital

**Comment by guwirth** [comment]
Have to test this tomorrow again. But I think was only working on my system with capital drive letter? But no more sure...  also don't know why drive letter is on some system upper case and on some lower case? Strange is also that DefaultFileSystem is not able to handle this?

**Comment by jmecosta** [comment]
nothing big for me found, time are almost the same as with previous versions

**Comment by guwirth** [comment]
@jmecosta Thanks for testing.

Will try to find a solution for the drive letter miracle an merge it then.

**Pull request merged**
